In [1]:
import numpy as np
import pandas as pd
from time import time
import operator
import sys
import pickle

In [2]:
df = pd.read_hdf("jsons/final_df_dl.h5",'main_df')

In [43]:
df

Author1  \
0               F.C. Williams   
1                    Hao Wang   
2               Ernest Hirsch   
3                   Ray Tsaih   
4        Edward W. Chencinski   
5               Kook-Yeol Yoo   
6                      A. Roy   
7                   Yuxin Jin   
8                B. G. Farley   
9                  J. Jamison   
10           Donna C. Mazzola   
11                     G. Lev   
12                 Jin-Yi Cai   
13                  Linmi Tao   
14                Guangyou Xu   
15                 Alan Feuer   
16                 Alan Feuer   
17                F. Luehring   
18             Javed A. Aslam   
19            Georg Ch. Pflug   
20             Mehrdad Ehsani   
21             John M. Miller   
22             John M. Miller   
23                 M. Ikeyama   
24               Dexter Kozen   
25              Soji Miyagawa   
26                  M. Tanaka   
27                H. Nakadate   
28                R. A. Dandl   
29                 M. Ikeyama   
...                       ...   
7499012         Junichi Urata   
7499013           Kazuo Hongo   
7499014       Naoya Muramatsu   
7499015        Masayuki Inaba   
7499016           Kazuo Hongo   
7499017          Tetsuo Endoh   
7499018          David Thirde   
7499019         Bradley Kjell   
7499020            C. Kireyev   
7499021      Horst Wildenauer   
7499022      Horst Wildenauer   
7499023      Horst Wildenauer   
7499024     Juan Miguel López   
7499025    Inmaculada Fajardo   
7499026     Juan Miguel López   
7499027  Ioannis M. Rekleitis   
7499028      Jean-Luc Bedwani   
7499029      Jean-Luc Bedwani   
7499030       Sebastien Gemme   
7499031            E. Paulson   
7499032         Ophir Frieder   
7499033          Erick Dupuis   
7499034              Bing Shi   
7499035              Bing Shi   
7499036              Bing Shi   
7499037           Dongxiao Li   
7499038            Ming Zhang   
7499039           Dongxiao Li   
7499040             Linmi Tao   
7499041           Guangyou Xu   

                                                        X1  \
0        [0.116421856, -0.206808, 0.13134108, -0.034457...   
1        [4.3905177, -2.7893012, 1.6123409, 4.6770196, ...   
2        [-0.024433045, -0.2912776, 1.0327069, 0.267105...   
3        [0.6482518, -0.053281967, 0.5312325, 0.5471009...   
4        [-0.42852956, 0.23266008, 1.1875072, 0.8594547...   
5        [1.3711678, -0.45269772, 0.16066076, 0.7606619...   
6        [2.8160937, 0.1355735, -1.3092846, 2.6904602, ...   
7        [-0.09414977, 0.025712641, 0.17621773, 0.07654...   
8        [-0.025311185, 0.024059597, 0.042996295, -0.04...   
9        [-0.13027838, 0.036430646, 0.17478262, -0.0269...   
10       [0.099964485, -0.0025849657, 0.096602954, 0.07...   
11       [0.1508436, -0.26267144, 0.010973016, 0.294077...   
12       [2.7859976, -8.342993, 3.0758057, 2.532676, 7....   
13       [0.977153, -0.7630269, 0.25412866, -0.4372957,...   
14       [2.3149107, -2.8648493, 0.6783641, 0.1576832, ...   
15       [0.55358094, -0.67790204, -0.5127347, 0.40257,...   
16       [0.55358094, -0.67790204, -0.5127347, 0.40257,...   
17       [0.11940511, -0.2517713, -0.08435344, 0.316567...   
18       [5.178381, -5.168986, 0.5066559, 3.4272468, 3....   
19       [1.5567763, -1.6434366, 1.5758193, 0.83192945,...   
20       [-0.31010646, 0.20874432, 0.45723236, 0.449021...   
21       [-0.5540337, -0.09221278, 0.022847254, -0.1153...   
22       [-0.5540337, -0.09221278, 0.022847254, -0.1153...   
23       [-0.16035816, -0.22141902, -0.20113064, 0.1856...   
24       [3.0344117, -1.8179876, 0.37900054, 2.4932508,...   
25       [-0.060621075, -0.20123048, -0.21632206, 0.244...   
26       [0.5368435, -0.93310064, 0.31262445, 1.8578904...   
27       [0.10765785, -0.22471333, -0.28836215, 0.08033...   
28       [0.054651383, 0.056541443, 0.0011104944, 0.085...   
29       [-0.16035816, -0.22141902, -0.20113064, 0.1856...   
...                                                  

In [42]:
df['y'].describe()

count    7.499042e+06
mean     3.856434e-03
std      7.268771e-03
min      0.000000e+00
25%      1.186446e-03
50%      2.103917e-03
75%      3.721888e-03
max      1.000000e+00
Name: y, dtype: float64

In [18]:
vector_dict=pickle.load(open("pickles/author_vector_dict_dl_final.pkl","rb"))

In [3]:
Author1=set(df.Author1)
Author2=set(df.Author2)
AuthorList=list(Author1|Author2)
print(len(AuthorList))
Author_old = list(set(df.Author1.iloc[:5999234])|set(df.Author2.iloc[:5999234]))

Author_new = list(set(df.Author1.iloc[5999234:])|set(df.Author2.iloc[5999234:]))

Author_new_test = list(np.setdiff1d(np.array(Author_old),np.setdiff1d(np.array(Author_old), np.array(Author_new), assume_unique=True), assume_unique=True))


1560120


In [53]:
score_list=pickle.load(open("pickles/score_dl.pkl","rb"))

In [27]:
type(score_list[('Mark McCann', 'Nicholas Pippenger')])

float

In [45]:
smin=min(score_list.values())
smax=max(score_list.values())
for k in score_list:
    score_list[k] = (score_list[k]-smin)/(smax-smin)

In [54]:
factor=1.0/sum(score_list.values())
for k in score_list:
    score_list[k] = score_list[k]*factor

In [55]:
def graphrec(name):
    target = name
    rec=[]
    #count=0
    Xf1=[]
    Xf2=[] 
    score=list()
    for i in range(len(AuthorList)):
        if(i%100000==0):
            print(i//100000,end=' ')
            sys.stdout.flush()
        try:
            score.append(score_list[(target,AuthorList[i])])
        except:
            score.append(0.0)


        # Xeval1=np.array(vector_dict[target])
            
        # Xeval2=np.array(vector_dict[AuthorList[i]])

        # #y  = extract.y

        # X1=np.array([])
        # X2=np.array([])

        # X1=np.append([X1],[Xeval1],axis=1)
        # X2=np.append([X2],[Xeval2],axis=1)

        # X1=X1.reshape(1,50,1)
        # X2=X2.reshape(1,50,1)
        # Xf1.append(X1)
        # Xf2.append(X2)
    
    # X1=np.array(Xf1).reshape(len(AuthorList),50,1)
    # X2=np.array(Xf2).reshape(len(AuthorList),50,1)
    # score = model.predict([X1,X2],batch_size=512,verbose=1)
    # score=list(score.reshape(len(AuthorList)))
    rec=list(zip(AuthorList,score))
    #print(count)
    rec.sort(key=operator.itemgetter(1),reverse=True)
    return rec[:150]

In [56]:
df_train=df.iloc[:5999234]
df_test=df.iloc[5999234:]

mrrn = 0
mrr = 0
rlo = {}
rln = {}
lor = []
lorn = []
prec = np.zeros(120)
recall = np.zeros(120)
f1 = np.zeros(120)
num=50

In [57]:
for i in range(50):
    print(i,end=' ')
    sys.stdout.flush()
    cnt = cnt1 = 0
    name = Author_new_test[i]
    col1 = df_test[df_test.Author1==name]
    col2 = df_test[df_test.Author2==name] 
    col = pd.concat([col1,col2])
    col_tr1 = df_train  [df_train.Author1==name]
    col_tr2 = df_train[df_train.Author2==name]
    col_tr = pd.concat([col_tr1,col_tr2])
    rel=[]
    rel1=[]
    for i in range(col.shape[0]):
        if col.iloc[i].Author1==name:
            rel.append(col.iloc[i].Author2)
        else:
            rel.append(col.iloc[i].Author1)

    for i in range(col_tr.shape[0]):
        if col_tr.iloc[i].Author1==name:
            rel1.append(col_tr.iloc[i].Author2)
        else:
            rel1.append(col_tr.iloc[i].Author1)

    lst = []
    lstn = []
    retr = graphrec(name)

    for i in range(120):
        if retr[i][0] in rel:
          lstn.append(1)
          cnt = cnt + 1
        else:
          lstn.append(0)


        if retr[i][0] in rel1:
          lst.append(1)
          cnt1 = cnt1 + 1
        else:
          lst.append(0)
        p = float(cnt1) / (i + 1)
        r = float(cnt1) / len(rel1)
        if p!=0 and r!=0:
            f = 2*p*r/(p+r)
        else:
            f = 0
        prec[i] = prec[i] + p
        recall[i] = recall[i] + r
        f1[i] = f1[i] + f

    #print cnt
    #print cnt1
    lor.append(lst)
    lorn.append(lstn)

0 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 1 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 2 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 3 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 4 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 5 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 6 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 7 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 8 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 9 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 10 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 11 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 12 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 13 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 14 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 15 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 17 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 18 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 19 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 20 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 21 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 22 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 23 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 24 0 1 2 3 4 5 6 7 8 9 10 

In [58]:
prec = prec/num
recall = recall/num
f1 = f1/num

In [59]:
f1

array([0.18259563, 0.27438469, 0.32714343, 0.35794465, 0.38062867,
       0.38338928, 0.38322156, 0.37247937, 0.36683776, 0.35856207,
       0.34923756, 0.34399964, 0.33839945, 0.33081116, 0.32479765,
       0.32054026, 0.31500438, 0.30869184, 0.3025396 , 0.29581829,
       0.28809627, 0.28157804, 0.27574877, 0.26881136, 0.26287469,
       0.25800742, 0.25340612, 0.24890108, 0.2435387 , 0.23814527,
       0.2337092 , 0.22931843, 0.22480716, 0.22061027, 0.21699653,
       0.2135529 , 0.21026821, 0.20713224, 0.20413563, 0.2012698 ,
       0.19831631, 0.19548062, 0.19296431, 0.19027854, 0.18796362,
       0.18553512, 0.18322918, 0.18100667, 0.17903208, 0.17686974,
       0.17478078, 0.17259497, 0.17064301, 0.16900921, 0.16726803,
       0.1654951 , 0.16366989, 0.16225335, 0.16069188, 0.15896221,
       0.15744076, 0.15620607, 0.15477002, 0.15318699, 0.15206991,
       0.1505649 , 0.1490978 , 0.1479011 , 0.14650425, 0.1453725 ,
       0.14427075, 0.14296931, 0.14169829, 0.14068264, 0.13931

In [50]:
f1

array([0.12307182, 0.16788374, 0.17445901, 0.16763048, 0.16367086,
       0.15823168, 0.15346767, 0.14776427, 0.14203524, 0.13724203,
       0.13271786, 0.12821998, 0.12355881, 0.11968761, 0.11619686,
       0.1125039 , 0.10944006, 0.10663146, 0.10424195, 0.10148957,
       0.09928937, 0.09720679, 0.0955028 , 0.09338206, 0.0916987 ,
       0.08993762, 0.08846404, 0.0868966 , 0.0854147 , 0.08371088,
       0.08256551, 0.08130402, 0.0799919 , 0.0788523 , 0.07794609,
       0.07708866, 0.07627671, 0.07550721, 0.07477741, 0.07408477,
       0.07342697, 0.07280187, 0.0722075 , 0.07136991, 0.0708335 ,
       0.07032271, 0.0696659 , 0.06903337, 0.06859263, 0.06791087,
       0.06725182, 0.06644776, 0.06583168, 0.06549006, 0.06499939,
       0.06443722, 0.06397898, 0.06369802, 0.06342976, 0.0627669 ,
       0.0622805 , 0.06180802, 0.0613489 , 0.06090262, 0.06046867,
       0.06004657, 0.05963588, 0.05923615, 0.058847  , 0.05846802,
       0.05809885, 0.05773914, 0.05738856, 0.05704677, 0.05656

In [60]:
prec

array([0.74      , 0.68      , 0.66      , 0.62      , 0.596     ,
       0.55666667, 0.52      , 0.4825    , 0.45555556, 0.43      ,
       0.40727273, 0.39      , 0.37538462, 0.36142857, 0.34933333,
       0.3375    , 0.32588235, 0.31333333, 0.30315789, 0.292     ,
       0.28095238, 0.27181818, 0.26434783, 0.255     , 0.2472    ,
       0.24076923, 0.23481481, 0.22857143, 0.22137931, 0.214     ,
       0.20903226, 0.20375   , 0.19818182, 0.19294118, 0.18914286,
       0.18555556, 0.18216216, 0.17894737, 0.17589744, 0.173     ,
       0.1697561 , 0.16666667, 0.16418605, 0.16136364, 0.15911111,
       0.15652174, 0.15404255, 0.15166667, 0.14979592, 0.1476    ,
       0.1454902 , 0.14307692, 0.14113208, 0.13962963, 0.13781818,
       0.13607143, 0.13403509, 0.13275862, 0.13118644, 0.12933333,
       0.12786885, 0.12677419, 0.12539683, 0.12375   , 0.12276923,
       0.12121212, 0.11970149, 0.11852941, 0.11710145, 0.116     ,
       0.11492958, 0.11361111, 0.11232877, 0.11135135, 0.10986

In [51]:
prec

array([0.58      , 0.47      , 0.40666667, 0.34      , 0.308     ,
       0.28333333, 0.26      , 0.24      , 0.22222222, 0.208     ,
       0.19636364, 0.18333333, 0.17230769, 0.16428571, 0.15733333,
       0.14875   , 0.14235294, 0.13666667, 0.13263158, 0.127     ,
       0.12285714, 0.11909091, 0.11652174, 0.1125    , 0.1096    ,
       0.10615385, 0.1037037 , 0.10071429, 0.09793103, 0.09466667,
       0.09290323, 0.090625  , 0.08848485, 0.08647059, 0.08514286,
       0.08388889, 0.0827027 , 0.08157895, 0.08051282, 0.0795    ,
       0.07853659, 0.07761905, 0.07674419, 0.07545455, 0.07466667,
       0.07391304, 0.07276596, 0.07166667, 0.07102041, 0.07      ,
       0.06901961, 0.06769231, 0.06679245, 0.0662963 , 0.06545455,
       0.06464286, 0.06385965, 0.06344828, 0.06305085, 0.062     ,
       0.06131148, 0.06064516, 0.06      , 0.059375  , 0.05876923,
       0.05818182, 0.05761194, 0.05705882, 0.05652174, 0.056     ,
       0.05549296, 0.055     , 0.05452055, 0.05405405, 0.05333

In [61]:
recall

array([0.11420742, 0.19991701, 0.26265458, 0.31441893, 0.35871327,
       0.38663206, 0.41103564, 0.42130165, 0.43560167, 0.44592316,
       0.45281322, 0.46244183, 0.47079862, 0.47581112, 0.48182155,
       0.48933862, 0.49484266, 0.4993881 , 0.5032885 , 0.50578206,
       0.50648083, 0.50773999, 0.50913338, 0.50937399, 0.51004492,
       0.51133193, 0.51259109, 0.51374388, 0.51393805, 0.51393805,
       0.51437284, 0.51470124, 0.51480762, 0.5150018 , 0.51543658,
       0.51587137, 0.51630615, 0.51674094, 0.51717573, 0.51761051,
       0.51791107, 0.51821163, 0.51864641, 0.51888702, 0.51932181,
       0.51962237, 0.51995077, 0.52027917, 0.52071396, 0.52095457,
       0.52119518, 0.52132941, 0.52157002, 0.52200481, 0.52233321,
       0.52257382, 0.522768  , 0.52320278, 0.52350334, 0.52363757,
       0.52387818, 0.52431297, 0.52455358, 0.52465996, 0.52509475,
       0.52520113, 0.52530751, 0.52560807, 0.52571445, 0.52601501,
       0.52631557, 0.52642195, 0.52652833, 0.52682889, 0.52682

In [52]:
recall

array([0.07557372, 0.11938059, 0.13600299, 0.14220303, 0.14870362,
       0.15257602, 0.15609986, 0.15795704, 0.15918589, 0.16047468,
       0.1614977 , 0.16222017, 0.16246078, 0.16289556, 0.16333035,
       0.16346458, 0.16379298, 0.16412138, 0.16455617, 0.16466255,
       0.16499096, 0.16529151, 0.1657263 , 0.16583268, 0.16613324,
       0.16632742, 0.16662797, 0.16682215, 0.16701632, 0.16701632,
       0.16731688, 0.16751105, 0.16761744, 0.16781161, 0.16811217,
       0.16841273, 0.16871329, 0.16901384, 0.1693144 , 0.16961496,
       0.16991552, 0.17021607, 0.17051663, 0.17062302, 0.17092357,
       0.17122413, 0.17141831, 0.17161248, 0.17191304, 0.17201942,
       0.1721258 , 0.1721258 , 0.17223219, 0.17253274, 0.17272692,
       0.1728333 , 0.17302748, 0.17332803, 0.17362859, 0.17362859,
       0.17373498, 0.17384136, 0.17394774, 0.17405412, 0.17416051,
       0.17426689, 0.17437327, 0.17447966, 0.17458604, 0.17469242,
       0.17479881, 0.17490519, 0.17501157, 0.17511795, 0.17511

In [62]:
pickle.dump(f1,open("pickles/f1_dl.pkl","wb"))
pickle.dump(prec,open("pickles/prec_dl.pkl","wb"))
pickle.dump(recall,open("pickles/recall_dl.pkl","wb"))